### ISSUE TITLE
Znalezienie bazy danych do treningu

### ISSUE THREAD

**Issue by jprokopczuk** [jprokopczuk/Find-my-home-and-country-roads#1]
Należy znaleźć bazę danych, w której znajdą się przykładowe dane, które wykorzystamy do opracowywania algorytmu.

**Comment by KarolNiem** [comment]
**Artykuł**: Building and road detection from large aerial imagery
**Technologia**: Konwolucyjne sieci neuronowe, a więc można byłoby użyć do implementacji Pythona i frameworka Tensorflow i interfejsu API Keras
**Zbiór danych**:
Massachusetts Building Dataset (budynki): https://www.kaggle.com/datasets/balraj98/massachusetts-buildings-dataset
Massachusetts Roads Dataset (drogi): https://www.kaggle.com/datasets/balraj98/massachusetts-roads-dataset

**Artykuł**: Mining Spatial Attention-Based Contextual Information for Road Extraction
**Technologia**: Konwolucyjne sieci neuronowe (konkretnie sieć MSACon)
**Zbiór danych**:
dataset for building and road detection (budynki i drogi): https://figshare.com/collections/Aerial_imagery_object_identification_dataset_for_building_and_road_detection_and_building_height_estimation/3290519

**Artykuł**: Aerial imagery for roof segmentation: A large-scale dataset towards automatic mapping of buildings 
**Technologia**: Konwolucyjne sieci neuronowe
**Zbiór danych**:
AIRS (Aerial Imagery for Roof Segmentation) (tylko budynki): https://www.airs-dataset.com/

**Artykuł**: Can Semantic Labeling Methods Generalize to Any City? The Inria Aerial Image Labeling Benchmark
**Technologia**: Konwolucyjne sieci neuronowe
**Zbiór danych**:
Inria Aerial Image Labeling (tylko budynki): https://project.inria.fr/aerialimagelabeling/


**Artykuł**: RoadTracer: Automatic Extraction of Road Networks from Aerial Images
**Technologia**: Autorska iteracyjna metoda RoadTracer opara o konwolucyjne sieci neuronowe
**Zbiór danych**: 
RoadTracer (tylko drogi): https://github.com/mitroadmaps/roadtracer/tree/master/dataset

**Który zbiór danych uważam za najlepszy?**
Moim zdaniem powinniśmy wybrać kombinację zbiorów Massachusetts Building Dataset w zadaniu wykrywania budynków oraz Massachusetts Roads Dataset w zadaniu wykrywania dróg. Przede wszystkim jest wiele artykułów podchodzących do tematu wykrywania dróg/budynków, które bazują właśnie na tych zbiorach. Wydają się one więc być najpopularniejsze. Będzie można zbadać różne podejścia i porównać wyniki opisane w różnych artykułach wykorzystujących te zbiory. Zbiór Massachusetts Roads Dataset składa się z 1171 zdjęć lotniczych stanu Massachusetts o wymiarach 1500x1500 pikseli (nie będzie więc problemu z ujednolicaniem rozmiarów zdjęć). Zbiór zawiera różnorodne zdjęcia przedstawiające zarówno obszary miejskie, przedmieścia i tereny pozamiejskie o łącznej powierzchni 2600 kilometrów kwadratowych. Drugi ze zbiorów jest mniej rozbudowany i składa się ze 151 obrazów, jednak posiada wszystkie inne zalety zbioru Massachusetts Roads Dataset.

**Comment by jprokopczuk** [comment]
**Artykuł**: Building detection from aerial images using invariant color features and shadow information, Beril Sırmac¸ek and Cem Unsalan, Computer Vision Research Laboratory
Department of Electrical and Electronics Engineering
Yeditepe University ˙Istanbul, 34755 TURKEY, IEEE
**Technologia**: Analiza kolorów, wykrywanie cieni budynków
**Zbiór danych**:
"Istanbul Data Set": Brak danych co do linka
