### ISSUE TITLE
Wybór technologii

### ISSUE THREAD

**Issue by jprokopczuk** [jprokopczuk/Find-my-home-and-country-roads#2]

**Comment by KarolNiem** [comment]
Moim zdaniem najlepiej do tego zadania nada się **python** ze względu na dużą liczbę frameworków ułatwiających analizę obrazu. Jeśli chodzi o różne podejścia do rozwiązania zadania segmentacji dróg i budynków zdecydowanie najczęściej spotykam się z podejściem opartym o konwolucyjne sieci neuronowe. W pythonie najpopularniejszym frameworkiem do sieci neuronowych jest **tensorflow** wraz z **API Keras Sequential**. Praca z tymi narzędziami będzie przedstawiona na 4 laboratorium z TWM, ale także jest bardzo dobrze opisana w oficjalnej dokumentacji. Alternatywą dla tensorflow wydaje się być **Pytorch**, który wyjątkowo dobrze sprawdza się w zastosowaniu segmentacyjnych sieci neuronowych. Problem analizy zdjęć lotniczych można byłoby także spróbować rozwiązać metodą tekstur (GLCM). To podejście jest jednak moim zdaniem nieco ryzykowne, ponieważ w przypadku analizy zdjęć z dużej wysokości albo zdjęć o niskiej rozdzielczości analiza tekstur w szczególności dróg, które zajmują małą liczbę pikseli całego obrazu może okazać się mało dokładna. Narzędzia do analizy tekstur dostarczane są w pythonie przez bibliotekę **skimage**. Jako punkt odniesienia możemy wybrać 3 podejście polegające na analizie i detekcji konturów. W pythonie można tego dokonać przy użyciu gotowych narzędzi biblioteki **OpenCV**. We wszystkich przypadkach trzeba będzie prawdopodobnie przekonwertować obrazy do skali szarości.
