### ISSUE TITLE
Opis tematu

### ISSUE THREAD

**Issue by jprokopczuk** [jprokopczuk/Find-my-home-and-country-roads#3]
Założenia i cel.

**Comment by kszewczak98** [comment]
Detekcja budynków oraz dróg ze zdjęć lotniczych może być używana w wielu dziedzinach, m.in. takich jak gospodarka przestrzenna, tworzenie map, urbanistyka, analiza użytkowania gruntów czy pomoc w przypadku katastrof. Tradycyjne metody rozpoznawania obiektów na zdjęciach lotniczych, takie jak ‘ręczna’ analiza przez ekspertów, są bardzo kosztowne i czasochłonne, ze względu na to, iż budynki i ulice mogą przybierać wiele różnych kształtów oraz być zakrywane przez inne 
obiekty, takie jak np. drzewa. 

Cel: Stworzenie systemu do automatycznego rozpoznawania budynków i dróg bezpośrednio ze zdjęć lotniczych.

Rodzaj danych i warunki pracy:  Zaproponowane w tym projekcie rozwiązanie będzie dokonywało automatycznej detekcji budynków i dróg jednocześnie ze zdjęć lotniczych  o formacie png i tiff i rozdzielczości 1m2/piksel. Zdjęcia mogą przedstawiać tereny mało zabudowane jak i te przedstawiające zabudowę miejską. Ponadto system ma również dokonywać detekcji dla zdjęć zawierających zbiorniki wodne i rzeki, nie myląc ich z budynkami i drogami. Efektem działania systemu ma być zdjęcie z po etykietowanymi pikselami: droga, budynek, inne.
