### ISSUE TITLE
Omówienie zbioru danych

### ISSUE THREAD

**Issue by jprokopczuk** [jprokopczuk/Find-my-home-and-country-roads#5]
Omówienie zbioru danych, który zostanie wykorzystany do treningu i testów.

**Comment by KarolNiem** [comment]
**Massachusetts Buildings Dataset**:
Składa się z 151 zdjęć lotniczych Bostonu i okolic. Każde ze zdjęć posiada wymiary 1500x1500 pikseli i pokrywa obszar 2,25 kilometrów kwadratowych, przez co całość zdjęć pokrywa około 340 kilometrów kwadratowych. Zbiór podzielony jest na zbiór treningowy (137 zdjęć), testowy (10 zdjęć) i walidacyjny (4 zdjęcia). Mapy docelowe uzyskano poprzez rasteryzację śladów budynków uzyskanych z projektu OpenStreetMap. Zbiór danych obejmuje głównie obszary miejskie i podmiejskie, a na etykietach znajdują się budynki wszystkich rozmiarów, w tym pojedyncze domy i garaże. Zbiory danych wykorzystują zdjęcia udostępnione przez stan Massachusetts. Wszystkie zdjęcia są przeskalowane do rozdzielczości 1 piksela na metr kwadratowy. Mapy docelowe dla zestawu danych zostały wygenerowane przy użyciu danych z projektu OpenStreetMap. Mapy docelowe dla części testowej i walidacyjnej zestawu danych zostały ręcznie skorygowane, aby oceny były dokładniejsze.

**Massachusetts Roads Dataset**:
Składa się z 1171 zdjęć lotniczych stanu Massachusetts. Każde zdjęcie ma rozmiar 1500×1500 pikseli i zajmuje powierzchnię 2,25 kilometra kwadratowego. Zbiór podzielono na zestaw treningowy (1108 obrazów), zestaw do walidacji (14 obrazów) i zestaw testowy (49 obrazów). Zestaw danych obejmuje szeroką gamę regionów miejskich, podmiejskich i wiejskich i obejmuje obszar ponad 2600 kilometrów kwadratowych. Mapy docelowe zostały wygenerowane przez rasteryzację osi dróg uzyskanych z projektu OpenStreetMap. Przy generowaniu etykiet zastosowano linię o grubości 7 pikseli i nie zastosowano wygładzania. Wszystkie zdjęcia są przeskalowane do rozdzielczości 1 piksela na metr kwadratowy.

Oba zbiory zostały stworzone przez Volodymyra Minha i są dostępne publicznie. Zostaną one połączone, aby umożliwić jednoczesne rozpoznawanie dróg i budynków. Z racji tego, że zbiór Massachusetts Roads Dataset zawiera wszystkie zdjęcia ze zbioru Massachusetts Buildings Dataset niezbędne będzie stworzenie nowego zbioru opartego o zdjęcia występujące w obu zbiorach, które posiadać będą 3 rodzaje etykiet: droga, budynek, pozostałe. Elementy zbioru poddawane będą preprocessingowi, który ograniczał będzie się do augmentacji danych. Dzięki temu zbiór danych zostanie wzbogacony o dodatkowe elementy, których wszystkie wartości pikseli będą normalizowane poprzez odjęcie od nich średniej wartości obliczonej na każdym zdjęciu i podzieleniu przez standardowe odchylenie obliczone na całym zbiorze danych. Każde ze zdjęć zostanie następnie obrócone o losowy kąt. Jako miary jakości analizowane będą precyzja i czułość. Precyzja definiowana jest jako stosunek liczby poprawnie rozpoznanych pikseli jako należących do dróg lub budynków do ogólnej liczby pikseli wykrytych na obrazach jako należące do dróg lub budynków. Czułość z kolei to stosunek liczby poprawnie rozpoznanych pikseli jako należących do dróg lub budynków do ogólnej liczby pikseli dróg lub budynków.
