### ISSUE TITLE
Projekt techniczny

### ISSUE THREAD

**Issue by jprokopczuk** [jprokopczuk/Find-my-home-and-country-roads#6]
Projekt techniczny rozwiązania (np. schemat struktury systemu).

**Comment by kszewczak98** [comment]
1. Preprocessing zbioru danych - gotowe
2. Architektura sieci - 
3. Porównanie - progowanie (miary jakości)-metoda nie obsługująca nietrywialnych przypadków
3.1. walidacja - w jaki sposób realizowana (parametry maski) - utworzenie maski wykrywającej drogi i budynki, która posłuży do klasyfikacji
